// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Demo$TestsAndFetch = require("../src/Demo.bs.js");

describe("Chec Network Errors", (function () {
        Jest.test("Loading State", (function (param) {
                return Jest.Expect[/* toBe */2]("Loading", Jest.Expect[/* expect */0](Demo$TestsAndFetch.emulateResponseResult(/* Loading */0)));
              }));
        Jest.test("General Success State", (function (param) {
                return Jest.Expect[/* toBe */2]("John", Jest.Expect[/* expect */0](Demo$TestsAndFetch.emulateResponseResult(/* Success */Block.__(1, [/* record */[
                                        /* name */"John",
                                        /* age */34
                                      ]]))));
              }));
        return Jest.test("Vladimir Success State", (function (param) {
                      return Jest.Expect[/* toBe */2]("Howdy Vladimir", Jest.Expect[/* expect */0](Demo$TestsAndFetch.emulateResponseResult(/* Success */Block.__(1, [/* record */[
                                              /* name */"Vladimir Novick",
                                              /* age */34
                                            ]]))));
                    }));
      }));

/*  Not a pure module */
