// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var match = Js_dict.get(peopleAge, "Vladimir");

if (match !== undefined) {
  console.log("Vladimir is" + String(match));
} else {
  console.log("Vladimir is not found");
}

var partial_arg = "Hey";

function testRec(param, param$1) {
  var tmp = { };
  if (partial_arg !== undefined) {
    tmp.test = Caml_option.valFromOption(partial_arg);
  }
  if (param !== undefined) {
    tmp.test3 = Caml_option.valFromOption(param);
  }
  return tmp;
}

var date = new Date();

console.log(date);

console.log(Path.dirname(""));

var result = JSON.parse("{\"name\": \"Luke\"}");

var n = result.name;

exports.testRec = testRec;
exports.date = date;
exports.result = result;
exports.n = n;
/* match Not a pure module */
