// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function make(param) {
  return "";
}

function print(log) {
  console.log(log);
  return /* () */0;
}

exports.print = print;
exports.make = make;
/* No side effect */
