// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Log$BasicProject = require("./Log.bs.js");

var a = Log$BasicProject.print("asd");

var LogWithFoo = /* module */[
  /* print */Log$BasicProject.print,
  /* make */Log$BasicProject.make,
  /* a */a
];

exports.LogWithFoo = LogWithFoo;
/* a Not a pure module */
