// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Log$BasicProject = require("./Log.bs.js");

function t(a) {
  return /* () */0;
}

var times = Caml_int32.imul;

function square(x) {
  return Caml_int32.imul(x, x);
}

var $$Math = /* module */[
  /* t */t,
  /* times */times,
  /* square */square
];

Log$BasicProject.make(/* () */0);

function Make(RC) {
  var repeat = function ($staropt$star, str) {
    var times = $staropt$star !== undefined ? $staropt$star : RC[/* count */0];
    if (times <= 0) {
      return "";
    } else {
      return str + repeat(times - 1 | 0, str);
    }
  };
  return /* module */[/* repeat */repeat];
}

exports.$$Math = $$Math;
exports.Make = Make;
/*  Not a pure module */
