// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function isServerCode(code) {
  return (code / 100 | 0) === 5;
}

function isClientCode(code) {
  return (code / 100 | 0) === 5;
}

function emulateResponseResult(response) {
  if (typeof response === "number") {
    return "Loading";
  } else if (response.tag) {
    var response$1 = response[0];
    if (response$1[/* name */0] === "Vladimir Novick") {
      return "Howdy Vladimir";
    } else {
      return response$1[/* name */0];
    }
  } else {
    var code = response[1];
    var message = response[0];
    var exit = 0;
    var switcher = code - 494 | 0;
    if (switcher > 5 || switcher < 0) {
      if (switcher !== -50) {
        exit = 1;
      } else {
        return "No response" + message;
      }
    } else if (switcher !== 4) {
      return "nginx error: " + message;
    } else {
      exit = 1;
    }
    if (exit === 1) {
      if (isServerCode(code)) {
        return "Network Error: " + message;
      } else if (isClientCode(code)) {
        return "Client Code:" + message;
      } else {
        return "Unknown code: " + (String(code) + (" message: " + message));
      }
    }
    
  }
}

exports.isServerCode = isServerCode;
exports.isClientCode = isClientCode;
exports.emulateResponseResult = emulateResponseResult;
/* No side effect */
