// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function post(post$1) {
  return /* record */[
          /* userId */Json_decode.field("userId", Json_decode.$$int, post$1),
          /* title */Json_decode.field("title", Json_decode.string, post$1),
          /* body */Json_decode.field("body", Json_decode.string, post$1)
        ];
}

var Decode = /* module */[/* post */post];

var url = "https://jsonplaceholder.typicode.com/posts/";

function fetchPosts(postId) {
  return fetch(url + String(postId)).then((function (prim) {
                    return prim.json();
                  })).then((function (json) {
                  var post$1 = post(json);
                  return Promise.resolve(post$1);
                })).catch((function (_err) {
                return Promise.resolve(undefined);
              }));
}

fetchPosts(2).then((function (result) {
        if (result !== undefined) {
          return Promise.resolve((console.log(result), /* () */0));
        } else {
          return Promise.resolve((console.log("no result"), /* () */0));
        }
      }));

exports.Decode = Decode;
exports.url = url;
exports.fetchPosts = fetchPosts;
/*  Not a pure module */
